AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: DevOpsBot Bootstrap API
Parameters:
  USERPOOLARN:
    Type: String
Resources:
  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: 'HEADER'
      Name: "ApiName"
      EndpointConfiguration: 
        Types: 
          - "REGIONAL"
      Body:
        swagger: "2.0"
        info:
          title: "DevOpsBot API"
          version: "1.0"
        paths:
          /example:
            get:
              responses:
                "200":
                  description: "200 response"
                  schema:
                    type: "string"
              x-amazon-apigateway-integration:
                httpMethod: "POST"
                type: "mock"
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      application/json: "{\"message\": \"Hello World\"}"
      Parameters:
        endpointConfigurationTypes: "REGIONAL"

  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: MyCognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref API
      ProviderARNs:
        - !Ref USERPOOLARN

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref API
      StageName: "dev"
