AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: DevOpsBot Bootstrap API
Parameters:
  USERPOOLARN:
    Type: String
Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      ApiKeySourceType: 'HEADER'
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn:
              !Ref USERPOOLARN
      Cors: "'*'"
      EndpointConfiguration: 
        Types: 
          - REGIONAL
      Name: ApiName
      StageName: dev
